bucket_order = [
    "methodPassive",
    "methodDirect",  # TODO: make one or the other with methodPassive
    "doseQuantity",
    "dose_QuantityValueOnly",
    "milligramValue",
    "doseXMilliValueOnly",
    "doseRange",
    "dose_QuantityValueAndMaxOnly",
    "milligramMax",
    "rateRatio",
    "rateQuantity",
    "rateRange",
    "durationValue",
    "durationMax",
    "frequencyBare",
    "frequencyWithMethod",
    "periodElement",
    "count",
    "whenBare",
    "whenWithMethod",
    "dayOfWeek",
    "timeOfDay",
    "route",
    "site",
    "asNeededCodeableConcept",
    "asNeededBoolean",
    "boundsDuration",
    "boundsPeriod",
    "boundsAPeriodStartEnd",
    "event",
    "maxDosePerPeriod",
    "maxDosePerAdministration",
    "maxDosePerLifetime",
    "extras",  # additionalInstruction
    "extrasPAUSE",
    "extrasALTER",
    "extras_b",
    "forElement",
]

number_dict_options = {
    "digit_to_word": {
        "1": "one",
        "2": "two",
        "3": "three",
        "4": "four",
        "5": "five",
        "6": "six",
        "7": "seven",
        "8": "eight",
        "9": "nine",
        "10": "ten",
    },
    "word_to_digit": {
        "one": "1",
        "two": "2",
        "three": "3",
        "four": "4",
        "five": "5",
        "six": "6",
        "seven": "7",
        "eight": "8",
        "nine": "9",
        "ten": "10",
    },
}

latin_dict = {
    "ac": "before food",
    "acm": "before breakfast",
    "acd": "before lunch",
    "acv": "before dinner",
    "bd": ". 2 times every day",
    "od": "every day",
    "om": "every morning",
    "pc": "after food",
    "pcm": "after breakfast",
    "pcd": "after lunch",
    "pcv": "after dinner",
    "prn": ". when required",
    "qds": ". to be taken 4 times every day",
    "qqh": "every 4 hours",
    "stat": "immediately",
    "tds": ". to be taken 3 times every day",
    "tid": ". 3 times every day",
    "mane": "every morning",
    "nocte": "every night",
    "hs": "before sleep",
    "wake": "upon waking",
    "c": "at a meal",
    "cm": "at breakfast",
    "cv": "at dinner",
    "morn": "morning",
    "aft": "afternoon",
    "eve": "evening",
    "phs": "after sleep",
    "mdu": "as directed",
    # Note: can't include "on": "every night", because of alternate meaning (e.g. on Friday)
    # Note: can't include "cd": "at lunch", because of possible mix up with control drug
}

replace_isolated_terms = {
    "after sleep": "once asleep",
    "hourly": "every hour",
    "daily": "every day",
    "weekly": "every week",
    "monthly": "every month",
    "once or twice": ". 1 or 2 times",
    # Note: can't replace once because alternate meaning, e.g. "once you feel better stop"
    "twice": ". 2 times",
    r"hrs": "hours",
    r"hr": "hour",
    r"(\d+)\s+(and)\sa?\s?(half)\s?(of)?\s?a?": r"$1.5 ",
    r"(\d+)\s+(and)\sa\s(half)": "$1.5 ",
    r"(half)\s?(of)?\s?a?": "0.5 ",
    r"(\d+)\s+and 3 quarters of a": "$1.75 ",
    r"(\d+)\s+(and)\s(3 quarters)\s?(of)?\s?a?": "$1.75 ",
    r"(3 quarters)\s?(of)?\s?a?": "0.75 ",
    r"(\d+)\s+(and)\sa?\s?(quarter)\s?(of)?\s?a?": "$1.25 ",
    r"a?(quarter)\s?(of)?\s?a?": "0.25 ",
    "upto": "up to",
}

replace_partofaword_terms = {
    # r"\(s\)": "s ", # Dont remove (s) as a different meaning
    r"(\d{1,2})[\/](\d{1,2})[\/](\d{2,4})": r"$1.$2.$3",
    r"(\d{1,2})[\-](\d{1,2})[\-](\d{2,4})": r"$1.$2.$3",
}

weird_terms = {
    r"(\d+)\s-(\d+)": r"$1 - $2",
}

clean_up_stragglers = {
    r"\(\)": "",
    r"\.": "",
}

nums = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]
exclude_list = [a + b for a in nums for b in nums] + [
    "one half",
    "1 half",
    "2time",
    "0ne",
    "oneto",
    "&amp;",
    "&gt;",
    "&lt;",
    "1 time",
    "one time",
]

date_reg_dmy = (
    r"^([0-2]?[1-9]|10|20|30|31)"  # day dd. 01-09 or 1-24
    r"([\/.\-](0?[0-9]|10|11|12)[\/.\-]"  # either month, 01-09 or 1-12
    r"|[\/.\-\s]"  # or add space option and mmm or Month
    r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|"
    r"January|February|March|April|May|June|July|August|September|October|November|December)"
    r"[\/.\-\s])"
    r"(19|20)[0-9]{2}$"  # year yyyy. 1900-2099
)

date_reg_ymd = (
    r"^(19|20)[0-9]{2}"  # year yyyy. 1900-2099
    r"([\/.\-](0?[0-9]|10|11|12)[\/.\-]"  # either month, 01-09 or 1-12h
    r"|[\/.\-\s]"  # or add space option and mmm or Month
    r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|"
    r"January|February|March|April|May|June|July|August|September|October|November|December)"
    r"[\/.\-\s])"
    r"([0-2]?[1-9]|10|20|30|31)$"  # day dd. 01-09 or 1-24
)

#  Add the plural of the list via processing rather than require both in the list. Display as 5 milligram
preprocess_units_of_measure = {
    #    "milligram": ["milligram", "mg"],
    #    "millilitre": ["millilitre", "ml"],
    #    "microgram": ["microgram"],
    #    "nanogram": ["nanogram"],
    #    "millimol": ["millimol", "mmol"],
    r"$1 x 5ml spoon": [
        r"(\d+)\s?x5ml spoon",
        r"(\d+)\s?x5mls spoon",
        r"(\d+)\s?x 5mls spoon",
        r"(\d+) 5mls? spoon",
    ],
    r"$1 x 2.5ml spoon": [
        r"(\d+)\s?x2.5ml spoon",
        r"(\d+)\s?x2.5mls spoon",
        r"(\d+)\s?x 2.5mls spoon",
        r"(\d+) 2.5mls? spoon",
    ],  #
}

odd_spellings = {
    "daily": "dayly",
    " ": "  ",
}

site_old_config = {
    "options": [
        "nostril",
        "rectum",
        "eye",
        "tongue",
        "area",
        "nail",
    ],
    "prefixes": ["in the", "to the", "in", "to", "into", "under", "on", ""],
    "next_prefixes": [
        "both",
        "affected",
        "each",
        "the",
        "painful",
        "left",
        "right",
        "infected",  # new
        "",
    ],
    "suffixes": ["s", "(s)", ""],
}

asNeededBoolean = [
    "as required",
    "when required",
    "if required",
    # "as req",  # removed as could mean requested
    # "when req",  # removed as could mean requested
    # "if req",  # removed as could mean requested
    "as needed",
    "if needed",
    "when needed",
    "as necessary",
    "if necessary",
    "when necessary",
]

# route - mostly secondary care
route = [
    "submucosal rectal",
    "inhalation",
    "implantation",
    "buccal",
    "intraperitoneal",
    "subretinal",
    "intrauterine",
    "perilesional",
    "intracavernous",
    "intracervical",
    "intracoronary",
    "intradermal",
    "intracardiac",
    "intralesional",
    "intradiscal",
    "intrapleural",
    "intralymphatic",
    "intraocular",
    "intrasternal",
    "perineural",
    "subconjunctival",
    "oromucosal",
    "intravesical",
    "periarticular",
    "ocular",
    "dental",
    "endocervical",
    "extra-amniotic",
    "gastroenteral",
    "endosinusial",
    "endotracheopulmonary",
    "intraamniotic",
    "intrabursal",
    "gingival",
    "intra-articular",
    "transmucosal",
    "epidural",
    "intraglandular",
    "intracerebroventricular",
    "intraosseous",
    "infiltration",
    "intraventricular route - cardiac",
    "body cavity",
    "regional perfusion",
    "nasal",
    "peribulbar ocular",
    "extracorporeal",
    "intravenous",
    "oral",
    "subcutaneous",
    "intraputaminal",
    "enteral",
    "intracameral",
    "sublabial",
    "nasojejunal",
    "intravitreal",
    "retrobulbar",
    "intratendinous",
    "intratumor",
    "epilesional",
    "percutaneous endoscopic gastrostomy tube",
    "intraepidermal",
    "pericardial",
    "intrathecal",
    "haemodialysis",
    "intramuscular",
    "iontophoresis",
    "haemodiafiltration",
    "translingual",
    "cutaneous",
    "peritendinous",
    "percutaneous",
    "submucosal",
    "otic",
    "haemofiltration",
    "intracatheter instillation",
    "intradialytic",
    "intracholangiopancreatic",
    "sublingual",
    "transdermal",
    "line lock",
    "periosseous",
    "gastrostomy",
    "jejunostomy",
    "nasogastric",
    "rectal",
    "peritumoral",
    "urethral",
    "vaginal",
    "intra-arterial",
]
extras_asDirected = [
    # fixed
    "as directed",  # Additional information
    r"\basd\b",
    r"\bad\b",
]
extras_symptoms_PAUSE = [
    "these tablets are addictive so do not take regularly",
    "potentially addictive",
    "not for long term use",
]
extras_symptoms_ALTER = [
    "may cause drowsiness",
]
extras_purpose = [
    # purpose #Use with asNeededCodeableConcept otherwise additionalinformation
]  # Qcall2 - What does Friday Collect mean?
extras_how = [
    "sparingly",
    "preferably",
    "thinly",
    "as moisturiser and as soap substitute",
    "to be supplied in a dosette",
    "in dosette",
    "via spacer",
    "as soap substitute",
    "at the same time every day",
    "without a break",  # Qcall2
    r"with your inhaler(\(s\)|s)?",
    r"with (plenty of )?(water|orange juice)",
    "with a full glass of water",
    "with spacer",
    "with insulin pen",
    "regularly",
    (
        r"(with|while|whilst|when)? ?"
        r"(taking|on|using)? ?"
        r"(regular)? ?"
        r"(paracetamol|ibuprofen|asprin|naproxen|prednisolone)"
    ),  # Qcall2
    "while sitting",
    "while standing",
    "while sitting or standing",
    "when washing hair",
]
extras_how_PAUSE = [
    "rinse mouth with water and spit out after use",
    "a thick layer and cover with dressing",
    "dosette",
    "remove old patch before new patch",
]
extras_qualifiers = ["after dialysis", "until review"]
extras_qualifiers_PAUSE = [
    "reduce dose if dizzy",
]

extra_random = [
    "to continue indefinitely",
    "in blister pack",
]

extra_random_PAUSE = [
    "please return your empty or unwanted inhalers to a pharmacy for disposal",
    "blister pack",
    "collect Friday",  # Qcall2: is this an additional instruction anyday of the week?
    "eps",  # Qcall2: what does this mean?
    "contains paracetamol and codeine",  # Qcall2: anywhere specific?
    "clean by soaking in warm soapy water",
    "rinse and allow to air-dry",
    "home delivery service",
    "indication: cvd prevention",
]

extras = (
    extras_asDirected + extras_purpose + extras_how + extra_random + extras_qualifiers
)

# These don't sound right unless a comma is added prior
extrasPAUSE = (
    extras_symptoms_PAUSE
    + extras_how_PAUSE
    + extra_random_PAUSE
    + extras_qualifiers_PAUSE
)

# These make the before invalid - e.g. 2 per day may cause drowsiness
extrasALTER = extras_symptoms_ALTER

# Extras which contain numbers need to go before matcher runs
extras_b = [
    r"replace every [0-9]*\s?(day|week|month|year)s?",
    "amber 2",
    "amber 3",
]

unit_config = {
    "options": [
        "tablet",
        "chewable tablet",
        "capsule",
        "dose",
        "puff",
        "drop",
        # "tab",  # removed as ambiguous
        "spoon",
        "spoonful",
        # "cap",  # removed as ambiguous
        "ampoule",
        "patch",
        "sachet",
        "pump",
        "caplet",
        # "spray",  # could be method or unit
        # "doses",  # new
        # "spoonfuls",  # new
        # "sprays",  # new
        "bottle",  # new
        "enema",
        "lozenge",
        "pastille",
        "pessary",
        "strip",
        "suppository",
        "vial",
        "dressing",
        "swab",
        "plaster",
        "applicator",
        "cup",
        "scoop",
        "injection",
    ],
    "prefixes": [""],
    "suffixes": ["", "s", "(s)", "es"],
}
period_unit_config = {
    "options": [
        "minute",
        "hour",
        "day",
        "week",
        "fortnight",
        "month",
        "annual",
        "year",  # Qcall2 add cycle?
    ],
    "prefixes": [
        "per",
        "a",
        "/",
        "each",
        "every",
    ],
    "suffixes": ["", "ly"],
}
special_unit_config = {
    "options": [
        "litres per minute",
        "micrograms per kilogram per hour",
        "milligrams per minute",
    ],
    "prefixes": [""],
    "suffixes": [""],
}

method_config = {
    "options": [
        "take",
        "inhale",
        "apply",
        "use",
        "insert",
        # "spray",  # mixes up with spray the unit
        "place",
        "chew",
        "instil",
        "infuse",
        "dissolve",
        "inject",
        # "suck",
        "massage",
        "swallow",
        "administer",
        "rinse",
        "gargle",
        "give",
    ],
    "past_participles": [
        "taken",
        "inhaled",
        "applied",
        "used",
        "inserted",
        "placed",
        "chewed",
        "instilled",
        "infused",
        "dissolved",
        "injected",
        # "sucked",
        "massaged",
        "swallowed",
        "administered",
        "rinsed",
        "gargled",
        "given",
    ],
    "prefixes": ["", "to be "],
    "suffixes": ["", "n", "d", "ed"],
}

# note - don't add pain, or anxiety to options. if so then only to extract for asNeededCodeable
when_old_config = {
    "options": [
        "empty stomach",
        "bowel movement",
        "lunchtime",
        "evening meal",
        "main meal",
        "morning",
        "noon",
        "afternoon",
        "evening",
        "night",
        "food",
        "meal",
        "breakfast",
        "lunch",
        "dinner",
        "tea time",
        "asleep",
        "sleep",
        "bedtime",
        "waking",
        "wake",
        "eat",
        "procedure",
    ],
    "prefixes": [
        "after",
        "before",
        "with",
        "on",
        "at",
        "once",
        "upon",
        "when",
        "each",
        "every",
        "in",
        "",
    ],
    "suffixes": [""],
}

weekday_config = {
    "options": [
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
        "sunday",
        "mon",
        "tue",
        "wed",
        "thu",
        "fri",
        "sat",
        "sun",
    ],
    "prefixes": [""],
    "suffixes": [""],
}

milli_config = {
    "options": [
        "mg",
        "ml",
        "milligram",
        "millilitre",
        "mgs",
        "mls",
        "milligrams",
        "millilitres",
        "mcg",
        "microgram",
        "mcgs",
        "micrograms",
        "gram",
        "g",
        "grams",
        "gs",
        "nanogram",
        "nanograms",
        "millimol",
        "millimols",
        "mmol",
        "mmols",
        "litre",
        "litres",
    ],
    "prefixes": [""],
    "suffixes": [""],
}

for_config = {
    "options": [
        "to help improve blood pressure control",
        "for controlling high blood pressure",
        "for controlling your blood pressure",
        "for help controlling blood pressure",
        "to help reduce your breathlessness",
        "to help reduce your cardiovascular",
        "to help reduce raised cholesterol",
        "to help control high cholesterol",
        "to help control your cholesterol",
        "to help improve your cholesterol",
        "to help reduce your constipation",
        "to help treat raised cholesterol",
        "to help control your high blood pressure",
        "to help control your high blood clots",
        "to help prevent protect stomach",
        "to help reduce high cholesterol",
        "to help reduce your cholesterol",
        "to help treat your osteoporosis",
        "to help treat your raised blood pressure",
        "to help treat your raised blood clots",
        "to reduce your high cholesterol",
        "to help control breathlessness",
        "to help improve breathlessness",
        "to help lower control diabetes",
        "to help lower high cholesterol",
        "to help lower your cholesterol",
        "to help prevent breathlessness",
        "to help prevent cardiovascular",
        "to help protect cardiovascular",
        "to help relieve breathlessness",
        "to help treat your cholesterol",
        "to lower your high cholesterol",
        "to prevent high blood pressure",
        "to lower your your cholesterol",
        "to protect your cardiovascular",
        "to relieve your breathlessness",
        "for lowering your cholesterol",
        "for treating high cholesterol",
        "to help control your diabetes",
        "to help improve your diabetes",
        "to help reduce breathlessness",
        "to help reduce cardiovascular",
        "to help reduce reduce stomach",
        "to prevent raised cholesterol",
        "to reduce control cholesterol",
        "to reduce your cardiovascular",
        "to treat prevent constipation",
        "for controlling palpitations",
        "for improving cardiovascular",
        "for relieving breathlessness",
        "to control your palpitations",
        "to help control constipation",
        "to help control palpitations",
        "to help control your stomach",
        "to help control your thyroid",
        "to help improve constipation",
        "to help improve palpitations",
        "to help lower cardiovascular",
        "to help lowering cholesterol",
        "to help prevent constipation",
        "to help prevent incontinence",
        "to help prevent osteoporosis",
        "to help prevent palpitations",
        "to help protect your kidneys",
        "to help protect your stomach",
        "to help relieve constipation",
        "to help relieve palpitations",
        "to lower your cardiovascular",
        "to reduce raised cholesterol",
        "for controlling cholesterol",
        "for lowering cardiovascular",
        "for preventing constipation",
        "for preventing incontinence",
        "for preventing osteoporosis",
        "for preventing palpitations",
        "for protecting your kidneys",
        "for protecting your stomach",
        "for your raised cholesterol",
        "to aid lowering cholesterol",
        "to control high cholesterol",
        "to control your cholesterol",
        "to help control cholesterol",
        "to help control indigestion",
        "to help control low thyroid",
        "to help control neuropathic",
        "to help control your angina",
        "to help improve cholesterol",
        "to help lowering high blood pressure",
        "to help lowering high blood clots",
        "to help prevent indigestion",
        "to help prevent neuropathic",
        "to help reduce constipation",
        "to help reduce palpitations",
        "to help reduce raised blood pressure",
        "to help reduce raised blood clots",
        "to help reduce your stomach",
        "to help relieve neuropathic",
        "to help treat your diabetes",
        "to help your breathlessness",
        "to improve control diabetes",
        "to improve your cholesterol",
        "to lower raised cholesterol",
        "to lower reduce cholesterol",
        "to prevent high cholesterol",
        "to reduce your palpitations",
        "to treat raised cholesterol",
        "for preventing your angina",
        "for relieving constipation",
        "to help aid breathlessness",
        "to help control high blood pressure",
        "to help control high blood clots",
        "to help control high heart",
        "to help control your blood pressure",
        "to help control your blood clots",
        "to help control your heart",
        "to help control your nerve",
        "to help control your sugar",
        "to help improve your blood pressure",
        "to help improve your blood clots",
        "to help improve your bowel",
        "to help improve your heart",
        "to help prevent high blood pressure",
        "to help prevent high blood clots",
        "to help protect your blood pressure",
        "to help protect your blood clots",
        "to help protect your bones",
        "to help low blood pressure",
        "to help protect your heart",
        "to help reduce cholesterol",
        "to help reduce indigestion",
        "to help reduce lower blood pressure",
        "to help reduce lower blood clots",
        "to help reduce your wheeze",
        "to help treat constipation",
        "to help treat osteoporosis",
        "to help treat palpitations",
        "to reduce help cholesterol",
        "to reduce high cholesterol",
        "to reduce your cholesterol",
        "for controlling your copd",
        "for improving cholesterol",
        "for protecting your heart",
        "for raised cardiovascular",
        "for reducing constipation",
        "for treating constipation",
        "for treating osteoporosis",
        "for treating raised blood pressure",
        "for treating raised blood clots",
        "for your high cholesterol",
        "to control breathlessness",
        "to control cardiovascular",
        "to help control irritable bowel symptoms",
        "to help control irritable bowel syndrome",
        "to help control irritable bladder",
        "to help control irritable bowel",
        "to help control irritable skin",
        "to help control your mood",
        "to help control your pain",
        "to help control your skin",
        "to help improve your mood",
        "to help lower cholesterol",
        "to help prevent fractures",
        "to help prevent low blood pressure",
        "to help prevent low blood clots",
        "to help prevent your gout",
        "to help reduce high blood pressure",
        "to help reduce high blood clots",
        "to help reduce your blood pressure",
        "to help reduce your blood clots",
        "to help reduce your heart",
        "to help reduce your nerve",
        "to help relieve irritable bowel symptoms",
        "to help relieve irritable bowel syndrome",
        "to help relieve irritable bladder",
        "to help relieve irritable bowel",
        "to help relieve irritable skin",
        "to help treat cholesterol",
        "to help treat low thyroid",
        "to help your osteoporosis",
        "to help your palpitations",
        "to improve breathlessness",
        "to improve cardiovascular",
        "to lower high cholesterol",
        "to lower your cholesterol",
        "to prevent breathlessness",
        "to prevent cardiovascular",
        "to protect cardiovascular",
        "to reduce protect stomach",
        "to reduce your high blood pressure",
        "to reduce your high blood clots",
        "to relieve breathlessness",
        "to treat high cholesterol",
        "for controlling diabetes",
        "for helping constipation",
        "for lowering cholesterol",
        "for treating cholesterol",
        "to aid your palpitations",
        "to control your diabetes",
        "to help control diabetes",
        "to help control low mood",
        "to help control pressure",
        "to help control prostate",
        "to help improve diabetes",
        "to help improve low iron",
        "to help improve low mood",
        "to help improve prostate",
        "to help lower high blood pressure",
        "to help lower high blood clots",
        "to help lower your blood pressure",
        "to help lower your blood clots",
        "to help lower your heart",
        "to help lower your sugar",
        "to help prevent diabetes",
        "to help prevent low mood",
        "to help prevent pressure",
        "to help prevent prostate",
        "to help preventing blood pressure",
        "to help preventing blood clots",
        "to help preventing heart",
        "to help protect pressure",
        "to help reduce irritable bowel symptoms",
        "to help reduce irritable bowel syndrome",
        "to help reduce irritable bladder",
        "to help reduce irritable bowel",
        "to help reduce irritable skin",
        "to help reduce raised bp",
        "to help reduce your pain",
        "to help reduce your risk",
        "to help relieve low mood",
        "to help relieve pressure",
        "to help relieve prostate",
        "to help treat high blood pressure",
        "to help treat high blood clots",
        "to help treat your heart",
        "to help your cholesterol",
        "to help your neuropathic",
        "to improve control blood pressure",
        "to improve control blood clots",
        "to improve your diabetes",
        "to lower raised pressure",
        "to lower your high blood pressure",
        "to lower your high blood clots",
        "to prevent high pressure",
        "to reduce breathlessness",
        "to reduce cardiovascular",
        "to relieve your low mood",
        "to treat raised pressure",
        "to reduce blood pressure",
        "to treat your high blood pressure",
        "to treat your high blood clots",
        "for controlling chronic",
        "for controlling high bp",
        "for high cardiovascular",
        "for lowering high blood pressure",
        "for lowering high blood clots",
        "for lowering your blood pressure",
        "for lowering your blood clots",
        "for preventing pressure",
        "for treating high blood pressure",
        "for treating high blood clots",
        "for your cardiovascular",
        "to control constipation",
        "to control incontinence",
        "to control osteoporosis",
        "to control palpitations",
        "to control your stomach",
        "to control your thyroid",
        "to help control chronic",
        "to help control high bp",
        "to help control stomach",
        "to help control thyroid",
        "to help control your bp",
        "to help improve anaemia",
        "to help improve chronic",
        "to help loosening mucus",
        "to help lower your risk",
        "to help prevent anaemia",
        "to help prevent chronic",
        "to help prevent stomach",
        "to help prevent strokes",
        "to help protect kidneys",
        "to help protect stomach",
        "to help reduce diabetes",
        "to help reduce low mood",
        "to help reduce pressure",
        "to help reduce prostate",
        "to help relieve chronic",
        "to help relieve stomach",
        "to help treat low sugar",
        "to help treat your mood",
        "to improve constipation",
        "to improve incontinence",
        "to improve palpitations",
        "to improve raised blood pressure",
        "to improve raised blood clots",
        "to improve your stomach",
        "to lower cardiovascular",
        "to lower lower pressure",
        "to prevent constipation",
        "to prevent higher blood pressure",
        "to prevent higher blood clots",
        "to prevent incontinence",
        "to prevent osteoporosis",
        "to prevent palpitations",
        "to prevent raised blood pressure",
        "to prevent raised blood clots",
        "to prevent your stomach",
        "to protect incontinence",
        "to protect your kidneys",
        "to protect your stomach",
        "to reduce high pressure",
        "to relieve constipation",
        "to relieve palpitations",
        "to treat breathlessness",
        "for controlling angina",
        "for improving diabetes",
        "for preventing stomach",
        "for preventing strokes",
        "for protecting kidneys",
        "for protecting stomach",
        "for raised cholesterol",
        "for treating low blood pressure",
        "for treating low blood clots",
        "to control cholesterol",
        "to control indigestion",
        "to control neuropathic",
        "to control your angina",
        "to help aid your sleep",
        "to help breathlessness",
        "to help cardiovascular",  # check
        "to help control angina",
        "to help control muscle",
        "to help control wheeze",
        "to help improve angina",
        "to help improve sputum",
        "to help lower pressure",
        "to help lowering blood pressure",
        "to help lowering blood clots",
        "to help prevent angina",
        "to help prevent low bp",
        "to help prevent muscle",
        "to help prevent wheeze",
        "to help reduce chronic",
        "to help reduce high bp",
        "to help reduce stomach",
        "to help reduce strokes",
        "to help reduce your bp",
        "to help relieve angina",
        "to help relieve muscle",
        "to help relieve wheeze",
        "to help treat diabetes",
        "to help treat low iron",
        "to help treat low mood",
        "to help treat prostate",
        "to help your irritable bowel symptoms",
        "to help your irritable bowel syndrome",
        "to help your irritable bladder",
        "to help your irritable bowel",
        "to help your irritable skin",
        "to improve cholesterol",
        "to improve neuropathic",
        "to lower control blood pressure",
        "to lower control blood clots",
        "to prevent cholesterol",
        "to prevent indigestion",
        "to prevent low thyroid",
        "to prevent neuropathic",
        "to prevent prophylaxis",
        "to prevent your angina",
        "to protect lower blood pressure",
        "to protect lower blood clots",
        "to reduce constipation",
        "to reduce incontinence",
        "to reduce osteoporosis",
        "to reduce palpitations",
        "to reduce prevent gout",
        "to reduce raised blood pressure",
        "to reduce raised blood clots",
        "to reduce reduce blood pressure",
        "to reduce reduce blood clots",
        "to reduce your kidneys",
        "to reduce your stomach",
        "to relieve indigestion",
        "to relieve neuropathic",
        "to treat high pressure",
        "to treat your diabetes",
        "to treat your low iron",
        "to treat your low mood",
        "for controlling blood pressure",
        "for controlling blood clots",
        "for controlling bowel",
        "for controlling heart",
        "for controlling sugar",
        "for lower cholesterol",
        "for preventing angina",
        "for raised high blood pressure",
        "for raised high blood clots",
        "for treating diabetes",
        "for your constipation",
        "for your incontinence",
        "for your osteoporosis",
        "for your palpitations",
        "for your raised blood pressure",
        "for your raised blood clots",
        "to aid breathlessness",
        "to aid improved sleep",
        "to control high blood pressure",
        "to control high blood clots",
        "to control high heart",
        "to control your blood pressure",
        "to control your blood clots",
        "to control your heart",
        "to control your sugar",
        "to help constipations",
        "to help control blood pressure",
        "to help control blood clots",
        "to help control bowel",
        "to help control heart",
        "to help control nerve",
        "to help control sleep",
        "to help control sugar",
        "to help improve bowel",
        "to help improve heart",
        "to help improve mucus",
        "to help improve sleep",
        "to help loosen sputum",
        "to help lower high bp",
        "to help lower stomach",
        "to help lower your bp",
        "to help prevent blood pressure",
        "to help prevent blood clots",
        "to help prevent bowel",
        "to help prevent clots",
        "to help prevent heart",
        "to help prevent sleep",
        "to help prevent stoke",
        "to help prevent ulcer",
        "to help protect blood pressure",
        "to help protect blood clots",
        "to help protect bones",
        "to help protect heart",
        "to help reduce angina",
        "to help reduce muscle",
        "to help reduce sputum",
        "to help reduce wheeze",
        "to help reduced blood pressure",
        "to help reduced blood clots",
        "to help relieve bowel",
        "to help relieve mucus",
        "to help relieve nerve",
        "to help relieve sleep",
        "to help treat anaemia",
        "to help treat chronic",
        "to help treat thyroid",
        "to help your diabetes",
        "to help your prostate",
        "to improve high blood pressure",
        "to improve high blood clots",
        "to improve lower mood",
        "to improve your blood pressure",
        "to improve your blood clots",
        "to improve your bones",
        "to improve your heart",
        "to improve your sugar",
        "to lower raised blood pressure",
        "to lower raised blood clots",
        "to prevent deficiency",
        "to prevent high sugar",
        "to prevent your heart",
        "to protect your blood pressure",
        "to protect your blood clots",
        "to protect your bones",
        "to protect your heart",
        "to protect your nerve",
        "to raised cholesterol",
        "to reduce cholesterol",
        "to reduce indigestion",
        "to reduce neuropathic",
        "to treat constipation",
        "to treat incontinence",
        "to treat osteoporosis",
        "to treat palpitations",
        "to treat raised blood pressure",
        "to treat raised blood clots",
        "to treat your chronic",
        "to treat your thyroid",
        "for controlled spasm",
        "for controlling copd",
        "for controlling gout",
        "for controlling mood",
        "for controlling pain",
        "for helping lower bp",
        "for high cholesterol",
        "for loosening sputum",
        "for lowering stomach",
        "for preventing blood pressure",
        "for preventing blood clots",
        "for preventing clots",
        "for preventing heart",
        "for protecting bones",
        "for protecting heart",
        "for reducing stomach",
        "for relieving wheeze",
        "for treating chronic",
        "for your cholesterol",
        "for your neuropathic",  # check
        "to control your copd",
        "to control your gout",
        "to control your mood",
        "to control your pain",
        "to control your skin",
        "to help constipation",
        "to help control copd",
        "to help control gout",
        "to help control mood",
        "to help control pain",
        "to help improve iron",
        "to help improve mood",
        "to help improve pain",
        "to help improve skin",
        "to help incontinence",
        "to help loosen mucus",
        "to help lower sputum",
        "to help osteoporosis",
        "to help palpitations",
        "to help prevent copd",
        "to help prevent gout",
        "to help prevent iron",
        "to help prevent mood",
        "to help prevent pain",
        "to help prevent risk",
        "to help prevent skin",
        "to help protect from",
        "to help protect skin",
        "to help reduce blood pressure",
        "to help reduce blood clots",
        "to help reduce bowel",
        "to help reduce clots",
        "to help reduce heart",
        "to help reduce mucus",
        "to help reduce nerve",
        "to help reduce spasm",
        "to help reduce sugar",
        "to help relieve pain",
        "to help relieve skin",
        "to help treat angina",
        "to help your anaemia",
        "to help your kidneys",
        "to help your stomach",
        "to help your thyroid",
        "to improve low blood pressure",
        "to improve low blood clots",
        "to improve raised bp",
        "to improve your iron",
        "to improve your mood",
        "to lower cholesterol",
        "to lower lower blood pressure",
        "to lower lower blood clots",
        "to prevent fractures",
        "to prevent irritable bowel symptoms",
        "to prevent irritable bowel syndrome",
        "to prevent irritable bladder",
        "to prevent irritable bowel",
        "to prevent irritable skin",
        "to prevent low blood pressure",
        "to prevent low blood clots",
        "to prevent low sugar",
        "to prevent your gout",
        "to protect your skin",
        "to reduce help blood pressure",
        "to reduce help blood clots",
        "to reduce high blood pressure",
        "to reduce high blood clots",
        "to reduce your blood pressure",
        "to reduce your blood clots",
        "to reduce your heart",
        "to reduce your sugar",
        "to relieve your copd",
        "to treat cholesterol",
        "to treat indigestion",
        "to treat low thyroid",
        "to treat neuropathic",
        "to treat your angina",
        "for helping kidneys",
        "for higher diabetes",
        "for improving blood pressure",
        "for improving blood clots",
        "for improving heart",
        "for improving sleep",
        "for loosening mucus",
        "for low cholesterol",
        "for preventing gout",
        "for protecting skin",
        "for raised pressure",
        "for relieving spasm",
        "for treating angina",
        "for your high blood pressure",
        "for your high blood clots",
        "for your your heart",
        "to aid constipation",
        "to aid palpitations",
        "to control diabetes",
        "to control low mood",
        "to control pressure",
        "to control prostate",
        "to help cholesterol",
        "to help indigestion",
        "to help lower blood pressure",
        "to help lower blood clots",
        "to help lower heart",
        "to help lower sugar",
        "to help neuropathic",
        "to help prophylaxis",
        "to help raise blood pressure",
        "to help raise blood clots",
        "to help reduce gout",
        "to help reduce pain",
        "to help reduce risk",
        "to help reduce size",
        "to help reduce skin",
        "to help treat blood pressure",
        "to help treat blood clots",
        "to help treat bowel",
        "to help treat heart",
        "to help treat mucus",
        "to help treat nerve",
        "to help your muscle",
        "to help your wheeze",
        "to high cholesterol",
        "to improve diabetes",
        "to improve low iron",
        "to improve low mood",
        "to improve prostate",
        "to lower help blood pressure",
        "to lower help blood clots",
        "to lower high blood pressure",
        "to lower high blood clots",
        "to lower your blood pressure",
        "to lower your blood clots",
        "to lower your heart",
        "to lower your sugar",
        "to prevent diabetes",
        "to prevent low iron",
        "to prevent low mood",
        "to prevent pressure",
        "to prevent prostate",
        "to protect diabetes",
        "to protect pressure",
        "to reduce irritable bowel symptoms",
        "to reduce irritable bowel syndrome",
        "to reduce irritable bladder",
        "to reduce irritable bowel",
        "to reduce irritable skin",
        "to reduce low blood pressure",
        "to reduce low blood clots",
        "to reduce raised bp",
        "to reduce your risk",
        "to reduce your skin",
        "to relieve low mood",
        "to relieve pressure",
        "to relieve prostate",
        "to treat deficiency",
        "to treat high blood pressure",
        "to treat high blood clots",
        "to treat high heart",
        "to treat high sugar",
        "to treat your blood pressure",
        "to treat your blood clots",
        "to treat your heart",
        "to your cholesterol",
        "for breathlessness",
        "for cardiovascular",  # check
        "for controlling bp",
        "for helping sputum",
        "for improving iron",
        "for improving mood",
        "for improving pain",
        "for low deficiency",  # check
        "for lowering blood pressure",
        "for lowering blood clots",
        "for lowering sugar",
        "for treating blood pressure",
        "for treating blood clots",
        "for treating heart",
        "for treating ulcer",
        "for your low blood pressure",
        "for your low blood clots",
        "to aid cholesterol",
        "to aid neuropathic",
        "to control chronic",
        "to control disease",
        "to control high bp",
        "to control stomach",
        "to control thyroid",
        "to control your bp",
        "to help aid sputum",
        "to help control bp",
        "to help high blood pressure",
        "to help high blood clots",
        "to help lower risk",
        "to help raise iron",
        "to help raise mood",
        "to help reduce cvd",
        "to help treat mood",
        "to help treat pain",
        "to help treat skin",
        "to help your blood pressure",
        "to help your blood clots",
        "to help your bones",
        "to help your bowel",
        "to help your heart",
        "to help your lungs",
        "to help your sleep",
        "to help your sugar",
        "to help your ulcer",
        "to improve anaemia",
        "to improve chronic",
        "to improve stomach",
        "to improve thyroid",
        "to low cholesterol",
        "to lower your risk",
        "to prevent anaemia",
        "to prevent chronic",
        "to prevent stomach",
        "to prevent strokes",
        "to prevent thyroid",
        "to protect kidneys",
        "to protect stomach",
        "to reduce diabetes",
        "to reduce low mood",
        "to reduce pressure",
        "to reduce prostate",
        "to relieve chronic",
        "to relieve stomach",
        "to treat irritable bowel symptoms",
        "to treat irritable bowel syndrome",
        "to treat irritable bladder",
        "to treat irritable bowel",
        "to treat irritable skin",
        "to treat low blood pressure",
        "to treat low blood clots",
        "to treat low sugar",
        "to treat raised bp",
        "to treat your copd",
        "for helping bones",
        "for helping bowel",
        "for helping heart",
        "for helping sleep",
        "for high pressure",
        "for lower stomach",
        "for lowering mood",
        "for lowering risk",
        "for reduced sleep",
        "for treating gout",
        "for treating mood",
        "for treating pain",
        "for your diabetes",
        "for your low iron",
        "for your low mood",
        "for your prostate",
        "to aid your sleep",
        "to control angina",
        "to control muscle",
        "to control sputum",
        "to control wheeze",
        "to help aid mucus",
        "to help aid sleep",
        "to help reduce bp",
        "to help reduce by",
        "to help your copd",
        "to help your iron",
        "to help your mood",
        "to help your pain",
        "to help your skin",
        "to improve angina",
        "to improve muscle",
        "to improve sputum",
        "to improve wheeze",
        "to lower pressure",
        "to prevent angina",
        "to prevent low bp",
        "to prevent muscle",
        "to prevent sputum",
        "to prevent wheeze",
        "to protects bones",
        "to reduce chronic",
        "to reduce kidneys",
        "to reduce stomach",
        "to reduce strokes",
        "to reduce thyroid",
        "to reduce your bp",
        "for heart failure",
        "to relieve angina",
        "to relieve muscle",
        "to relieve sputum",
        "to relieve wheeze",
        "to treat diabetes",
        "to treat low iron",
        "to treat low mood",
        "to treat pressure",
        "to treat prostate",
        "for aiding sleep",
        "for constipation",
        "for helping mood",
        "for helping pain",
        "for high thyroid",
        "for higher blood pressure",
        "for higher blood clots",
        "for improving bp",
        "for incontinence",
        "for low pressure",
        "for osteoporosis",
        "for palpitations",
        "for raised blood pressure",
        "for raised blood clots",
        "for raised heart",
        "for raised level",
        "for raised sugar",
        "for reduced iron",
        "for your anaemia",
        "for your chronic",
        "for your kidneys",
        "for your stomach",
        "for your thyroid",
        "to control blood pressure",
        "to control blood clots",
        "to control bowel",
        "to control clots",
        "to control heart",
        "to control mucus",
        "to control nerve",
        "to control pains",
        "to control sleep",
        "to control spasm",
        "to control sugar",
        "to help diabetes",
        "to help low iron",
        "to help low mood",
        "to help lower bp",
        "to help pressure",
        "to help prostate",
        "to help raise bp",
        "to help sleeping",
        "to high pressure",  # check
        "to improve blood pressure",
        "to improve blood clots",
        "to improve bones",
        "to improve bowel",
        "to improve heart",
        "to improve level",
        "to improve nerve",
        "to improve sleep",
        "to improve sugar",
        "to improve ulcer",
        "to loosen muscle",
        "to loosen sputum",
        "to lower high bp",
        "to lower stomach",
        "to lower thyroid",
        "to lower your bp",
        "to prevent clots",
        "to prevent level",  # check
        "to prevent mucus",
        "to prevent nerve",  # check
        "to prevent sleep",  # check
        "to prevent spasm",
        "to prevent stoke",
        "to prevent sugar",  # check
        "to prevent ulcer",
        "to protect blood pressure",
        "to protect blood clots",
        "to protect bones",
        "to protect heart",
        "to protect nerve",
        "to reduce angina",
        "to reduce low bp",  # check
        "to reduce muscle",
        "to reduce sputum",
        "to reduce wheeze",
        "to relieve bowel",
        "to relieve mucus",
        "to relieve nerve",
        "to relieve spasm",
        "to treat anaemia",
        "to treat chronic",
        "to treat high bp",
        "to treat kidneys",
        "to treat stomach",
        "to treat thyroid",
        "for cholesterol",
        "for high angina",
        "for higher risk",  # check
        "for indigestion",
        "for low thyroid",  # check
        "for lower blood pressure",
        "for lower blood clots",
        "for lower bowel",
        "for lower sugar",
        "for lowering bp",
        "for neuropathic",  # check
        "for prophylaxis",
        "for your angina",
        "for your muscle",
        "for your wheeze",
        "to aid diabetes",
        "to aid low mood",
        "to aid pressure",
        "to control copd",
        "to control gout",
        "to control mood",
        "to control pain",
        "to control skin",
        "to help anaemia",
        "to help high bp",
        "to help kidneys",
        "to help stomach",
        "to help thyroid",
        "to help your bp",
        "to higher level",  # check
        "to improve copd",
        "to improve gout",
        "to improve iron",
        "to improve mood",
        "to improve pain",
        "to improve skin",
        "to loosen bowel",
        "to loosen mucus",
        "to prevent copd",
        "to prevent gout",
        "to prevent iron",
        "to prevent mood",  # check
        "to prevent pain",
        "to prevent risk",
        "to prevent skin",
        "to protect gout",  # check
        "to protect skin",
        "to reduce bowel",
        "to reduce clots",
        "to reduce heart",
        "to reduce level",  # check
        "to reduce mucus",
        "to reduce nerve",
        "to reduce spasm",
        "to reduce stoke",
        "to reduce sugar",
        "to reduce ulcer",
        "to relieve copd",
        "to relieve gout",
        "to relieve pain",
        "to relieve skin",
        "to treat angina",
        "to treat low bp",
        "to treat muscle",
        "to treat wheeze",
        "for deficiency",  # check
        "for high blood pressure",
        "for high blood clots",
        "for high heart",  # check
        "for high level",  # check
        "for high sugar",
        "for nerve pain",
        "for lower pain",
        "for lower risk",  # check
        "for raised cvd",
        "for your blood pressure",
        "for your blood clots",
        "for your bones",
        "for your bowel",
        "for your heart",
        "for your lungs",
        "for your mucus",
        "for your nerve",
        "for your sleep",
        "for your sugar",
        "for your ulcer",
        "to aid anaemia",
        "to aid chronic",
        "to aid stomach",
        "to cholesterol",
        "to control cvd",
        "to help angina",
        "to help low bp",
        "to help muscle",
        "to help relief",
        "to help sputum",
        "to help wheeze",
        "to higher risk",  # check
        "to loosen skin",
        "to low kidneys",  # check
        "to lower blood pressure",
        "to lower blood clots",
        "to lower heart",
        "to lower level",
        "to lower sugar",
        "to neuropathic",  # check
        "to prevent cvd",
        "to prophylaxis",  # check
        "to raise blood pressure",
        "to raise blood clots",
        "to raised skin",
        "to reduce copd",
        "to reduce gout",
        "to reduce iron",
        "to reduce mood",
        "to reduce pain",
        "to reduce risk",
        "to reduce size",
        "to reduced cvd",  # check
        "to treat blood pressure",
        "to treat blood clots",
        "to treat bones",
        "to treat bowel",
        "to treat clots",
        "to treat heart",
        "to treat lungs",
        "to treat mucus",  # check
        "to treat nerve",  # check
        "to treat sleep",
        "to treat spasm",
        "to treat ulcer",
        "to your angina",  # check
        "for high mood",  # check
        "for high risk",  # check
        "for low blood pressure",
        "for low blood clots",
        "for low heart",  # check
        "for low level",
        "for low sugar",
        "for raised bp",
        "for your copd",
        "for your gout",
        "for your iron",
        "for your mood",
        "for your pain",
        "for your skin",
        "to aid muscle",
        "to aid relief",
        "to aid sputum",
        "to control bp",
        "to help blood pressure",
        "to help blood clots",
        "to help bones",
        "to help bowel",
        "to help heart",
        "to help lungs",
        "to help mucus",  # check
        "to help nerve",  # check
        "to help sleep",
        "to help spasm",
        "to help sugar",
        "to help ulcer",
        "to improve bp",
        "to lower gout",  # check
        "to lower mood",  # check
        "to lower pain",
        "to lower risk",
        "to prevent bp",  # check
        "to protect bp",
        "to raise iron",
        "to raise mood",
        "to reduce cvd",
        "to treat copd",
        "to treat gout",
        "to treat iron",
        "to treat mood",
        "to treat pain",
        "to treat skin",
        "for diabetes",
        "for high cvd",
        "for low iron",
        "for low mood",
        "for lower bp",
        "for pressure",
        "for prostate",
        "for sleeping",
        "to aid blood pressure",
        "to aid blood clots",
        "to aid bowel",
        "to aid heart",
        "to aid mucus",
        "to aid nerve",
        "to aid sleep",
        "to aid spasm",
        "to aid ulcer",
        "to help copd",
        "to help gout",
        "to help iron",
        "to help mood",
        "to help pain",
        "to help skin",
        "to lower cvd",
        "to raised bp",
        "to reduce bp",
        "for anaemia",
        "for disease",
        "for high bp",
        "for kidneys",
        "for stomach",
        "for strokes",
        "for thyroid",
        "for your bp",
        "to aid copd",
        "to aid iron",
        "to aid mood",
        "to aid pain",
        "to aid skin",
        "to help cvd",
        "to lower bp",
        "to raise bp",
        "to treat bp",
        "for angina",
        "for low bp",
        "for muscle",
        "for relief",
        "for sputum",
        "for ulcers",
        "for wheeze",
        "for blood pressure",
        "for blood clots",
        "for bones",
        "for bowel",
        "for clots",
        "for heart",
        "for lungs",
        "for mucus",
        "for pains",
        "for sleep",
        "for spasm",
        "for sugar",
        "for ulcer",
        "to aid bp",
        "for copd",
        "for gout",
        "for iron",
        "for mood",
        "for pain",
        "for cvd",
        "for bp",
    ]
}

when_config = {
    "options": [
        "after every bowel movement",
        "before each bowel movement",
        "after each bowel movement",
        "at 30minutes before food",
        "with each bowel movement",
        "at 2 hours before sleep",
        "at once after breakfast",
        "before the evening meal",
        "after a bowel movement",
        "after the evening meal",
        "at once in the morning",
        "at once with breakfast",
        "at once with main meal",
        "before bowel movements",
        "each with evening meal",
        "with each evening meal",
        "with the evening meals",
        "after bowel movements",
        "after every main meal",
        "at once every evening",
        "at once every morning",
        "before bowel movement",
        "before each main meal",
        "each in the afternoon",
        "with an empty stomach",
        "with the evening meal",
        "after bowel movement",
        "after each main meal",
        "at once each morning",
        "before evening meals",
        "before the breakfast",
        "before the main meal",
        "before the procedure",
        "every in the evening",
        "every in the morning",
        "in the empty stomach",
        "with an evening meal",
        "with bowel movements",
        "with every breakfast",
        "with every main meal",
        "after evening meals",
        "after the breakfast",
        "after the main meal",
        "at the evening meal",
        "before each bedtime",
        "before evening meal",
        "each in the evening",
        "each in the morning",
        "each with breakfast",
        "in an empty stomach",
        "in the evening meal",
        "on an empty stomach",
        "with each main meal",
        "with the main meals",
        "after evening meal",
        "at every main meal",
        "at once after food",
        "before a breakfast",
        "with empty stomach",
        "with evening meals",
        "with every morning",
        "with the breakfast",
        "with the main meal",
        "after a main meal",
        "at once with food",
        "at once with meal",
        "before every meal",
        "before main meals",
        "each at breakfast",
        "each at lunchtime",
        "each evening meal",
        "each in the night",
        "in the afternoons",
        "with evening meal",
        "after every meal",
        "after main meals",
        "at every evening",
        "at every morning",
        "at once at lunch",
        "at once at night",
        "before breakfast",
        "before each meal",
        "before lunchtime",
        "before main meal",
        "before procedure",
        "before the lunch",
        "before the night",
        "each at tea time",
        "in the afternoon",
        "in the breakfast",
        "in the lunchtime",
        "on empty stomach",
        "on every evening",
        "on every morning",
        "on the afternoon",
        "with a main meal",
        "with the evening",
        "with the morning",
        "after breakfast",
        "after each meal",
        "after lunchtime",
        "after main meal",
        "at each evening",
        "at each morning",
        "at evening meal",
        "before sleeping",
        "before tea time",
        "before the food",
        "before the meal",
        "every afternoon",
        "every breakfast",
        "every lunchtime",
        "in an afternoon",
        "in evening meal",
        "in the evenings",
        "in the mornings",
        "on an afternoon",
        "on each evening",
        "on each morning",
        "on the mornings",
        "with breakfasts",
        "with every meal",
        "with main meals",
        "after the food",
        "after the meal",
        "at every night",
        "at the evening",
        "at the morning",
        "before bedtime",
        "before evening",
        "before morning",
        "each afternoon",
        "each breakfast",
        "each lunchtime",
        "each main meal",
        "each with food",
        "every tea time",
        "in the bedtime",
        "in the evening",
        "in the morning",
        "on every night",
        "on the evening",
        "on the morning",
        "with afternoon",
        "with breakfast",
        "with each meal",
        "with lunchtime",
        "with main meal",
        "with the meals",
        "at each night",
        "at main meals",
        "before a meal",
        "before dinner",
        "before eating",
        "each at lunch",
        "each at night",
        "each tea time",
        "every bedtime",
        "every evening",
        "every morning",
        "in an evening",
        "in the nights",
        "on afternoons",
        "on an evening",
        "on each night",
        "on the nights",
        "with sleeping",
        "with tea time",
        "with the food",
        "with the meal",
        "after a food",
        "after a meal",
        "after dinner",
        "after eating",
        "after waking",
        "at afternoon",
        "at breakfast",
        "at each meal",
        "at lunchtime",
        "at main meal",
        "at procedure",
        "at the night",
        "before lunch",
        "before meals",
        "before night",
        "before sleep",
        "each at noon",
        "each bedtime",
        "each evening",
        "each morning",
        "in afternoon",
        "in the lunch",
        "in the night",
        "on a morning",
        "on the night",
        "with a lunch",
        "with bedtime",
        "with evening",
        "with morning",
        "after lunch",
        "after meals",
        "at tea time",
        "before food",
        "before meal",
        "before noon",
        "each dinner",
        "every lunch",
        "every night",
        "in evenings",
        "in mornings",
        "in the noon",
        "on evenings",
        "on mornings",
        "upon waking",
        "when eating",
        "when waking",
        "with a food",
        "with a meal",
        "with dinner",
        "with eating",
        "after food",
        "after meal",
        "after noon",
        "at bedtime",
        "at evening",
        "at morning",
        "each lunch",
        "each night",
        "every meal",
        "in evening",
        "in morning",
        "on a night",
        "on evening",
        "when wakes",
        "with foods",
        "with lunch",
        "with meals",
        "with night",
        "with sleep",
        "at a meal",
        "at dinner",
        "at waking",
        "each meal",
        "each noon",
        "on nights",
        "on waking",
        "with food",
        "with meal",
        "at lunch",
        "at meals",
        "at night",
        "at meal",
        "at noon",
    ]
}

site_config = [
    "in the affected nostril",
    "to the affected nostril",
    "into affected nostrils",
    "in the affected areas",
    "into affected nostril",
    "to the affected areas",
    "to the affected nails",
    "in the affected area",
    "in the affected eyes",
    "in the right nostril",
    "to affected nostrils",
    "to the affected area",
    "to the affected eyes",
    "to the affected nail",
    "to the infected area",
    "to the infected nail",
    "to the painful areas",
    "to the right nostril",
    "in affected nostril",
    "in the affected eye",
    "in the left nostril",
    "into affected areas",
    "to affected nostril",
    "to infected nostril",
    "to the affected eye",
    "to the left nostril",
    "to the painful area",
    "into affected area",
    "into affected eyes",
    "into both nostrils",
    "into painful areas",
    "into right nostril",
    "affected nostrils",
    "in affected areas",
    "into affected eye",
    "into each nostril",
    "into left nostril",
    "into painful area",
    "into the nostrils",
    "on affected areas",
    "on infected areas",
    "to affected areas",
    "to affected nails",
    "to infected areas",
    "to infected nails",
    "affected nostril",
    "in affected area",
    "in affected eyes",
    "in both nostrils",
    "in painful areas",
    "in right nostril",
    "in the right eye",
    "into the nostril",
    "on affected area",
    "on affected eyes",
    "on affected nail",
    "on both nostrils",
    "on infected area",
    "on painful areas",
    "to affected area",
    "to affected eyes",
    "to affected nail",
    "to both nostrils",
    "to infected area",
    "to infected nail",
    "to painful areas",
    "to right nostril",
    "to the right eye",
    "under the tongue",
    "in affected eye",
    "in each nostril",
    "in left nostril",
    "in the left eye",
    "into the rectum",
    "into the tongue",
    "on affected eye",
    "on each nostril",
    "on painful area",
    "to affected eye",
    "to each nostril",
    "to left nostril",
    "to painful area",
    "to the left eye",
    "to the nostrils",
    "affected areas",
    "affected nails",
    "in the nostril",
    "infected areas",
    "into both eyes",
    "into right eye",
    "to the nostril",
    "affected area",
    "affected eyes",
    "both nostrils",
    "in the rectum",
    "infected area",
    "infected nail",
    "into each eye",
    "into left eye",
    "into nostrils",
    "into the area",
    "into the eyes",
    "on the rectum",
    "on the tongue",
    "painful areas",
    "right nostril",
    "to the rectum",
    "to the tongue",
    "affected eye",
    "each nostril",
    "in each area",
    "in right eye",
    "into nostril",
    "into the eye",
    "left nostril",
    "on both eyes",
    "on right eye",
    "on the nails",
    "painful area",
    "the nostrils",
    "to both eyes",
    "to each area",
    "to right eye",
    "to the areas",
    "under tongue",
    "in each eye",
    "in left eye",
    "in nostrils",
    "in the area",
    "in the eyes",
    "into rectum",
    "on each eye",
    "on left eye",
    "on the area",
    "the nostril",
    "to each eye",
    "to left eye",
    "to nostrils",
    "to the area",
    "to the eyes",
    "under nails",
    "in nostril",
    "in the eye",
    "the rectum",
    "the tongue",
    "to nostril",
    "to the eye",
    "under eyes",
    "both eyes",
    "in rectum",
    "into area",
    "into eyes",
    "on tongue",
    "right eye",
    "the areas",
    "the nails",
    "to rectum",
    "to tongue",
    "each eye",
    "in areas",
    "in nails",
    "into eye",
    "left eye",
    "nostrils",
    "on nails",
    "the area",
    "the eyes",
    "the nail",
    "to areas",
    "to nails",
    "in area",
    "in eyes",
    "nostril",
    "on area",
    "on nail",
    "the eye",
    "to area",
    "to eyes",
    "to nail",
    "in eye",
    "on eye",
    "rectum",
    "to eye",
    "tongue",
    "areas",
    "nails",
    "area",
    "eyes",
    "nail",
    "eye",
]

# ---------------------------------------------------------------------------
# Priority Exceptions
# ---------------------------------------------------------------------------
# Cases where a sub-part element intentionally has higher priority than
# a compound element that contains it. In all other overlaps, the longer
# (more detailed) match wins automatically.

PRIORITY_EXCEPTIONS = {
    (
        "methodDirect",
        "frequencyWithMethod",
    ): "method extracted first, rescue gives compound the span",
    (
        "methodPassive",
        "frequencyWithMethod",
    ): "method extracted first, rescue gives compound the span",
    (
        "methodDirect",
        "whenWithMethod",
    ): "method extracted first, rescue gives compound the span",
    (
        "methodPassive",
        "whenWithMethod",
    ): "method extracted first, rescue gives compound the span",
}

ISOLATED_ELEMENTS = {loser for _, loser in PRIORITY_EXCEPTIONS}


# ---------------------------------------------------------------------------
# Numeric Validation Rules
# functions include: [
# - ("no_negatives",)
# - ("avoid_zero",)
# - ("below", N)
# - ("must_be_whole_num",)
# - ("must_be_greater_than", N)
# - ("avoid_emergency_numbers",)
# - ("avoid_years",)
# - ("avoid_times",)
# - ("only_halves_and_quarters",)
# - ]
# ---------------------------------------------------------------------------

EMERGENCY_NUMBERS = {"999", "111", "112", "911", "101"}
YEAR_RANGE = (1900, 2030)

# ── Thresholds ────────────────────────────────────────────────────────────────
HIGH_DOSE = 100
LOW_DOSE = 10
HIGH_FREQUENCY = 20
LOW_FREQUENCY = 10
HIGH_PERIOD = 100
LOW_PERIOD = 10
HIGH_MILLIGRAM = 5000
LOW_MILLIGRAM = 200
HIGH_DURATION = 365
LOW_DURATION = 52
HIGH_OFFSET = 120
LOW_OFFSET = 60
HIGH_MAX_DOSE = 100
LOW_MAX_DOSE = 20
HIGH_RATE = 100
LOW_RATE = 20
HIGH_COUNT = 20
LOW_COUNT = 10

# ── Validation groups ─────────────────────────────────────────────────────────

VALIDATION_GROUPS = {
    # ── Dose (e.g. "4 tablets", "1-2 puffs") ─────────────────────────────────
    "dose": {
        "confident": {
            "fields": [
                "doseQuantity_quantity",
                "doseRange_low",
                "doseRange_high",
            ],
            "rules": [
                ("no_negatives",),
                ("below", HIGH_DOSE),
                ("only_halfs_and_quarters",),
            ],
        },
        "risk_averse": {
            "fields": [
                "dose_QuantityValueOnly_value",
                "dose_QuantityValueAndMaxOnly_value",
                "dose_QuantityValueAndMaxOnly_valueMax",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", LOW_DOSE),
                ("avoid_emergency_numbers",),
                ("avoid_years",),
                ("avoid_times",),
                ("only_halfs_and_quarters",),
            ],
        },
        "max_rules": {
            "doseRange_high": ("must_be_greater_than", "doseRange_low"),
            "dose_QuantityValueAndMaxOnly_valueMax": (
                "must_be_greater_than",
                "dose_QuantityValueAndMaxOnly_value",
            ),
            "dose_QuantityValueAndMaxOnly_value": ("avoid_zero", False),
        },
    },
    # ── Dose x Milli (e.g. "120 x 42ml") ─────────────────────────────────────
    "dose_x_milli": {
        "confident": {
            "fields": [
                "doseXMilliValueOnly_value",
                "doseXMilliValueOnly_val_milli",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", 1),
                ("must_be_whole_num",),
            ],
        },
    },
    # ── Rate (e.g. "at a rate of 2 per 3 days") ──────────────────
    "rate_ratio": {
        "confident": {
            "fields": [
                "rateRatio_numerator",
                "rateRatio_denominator",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", HIGH_RATE),
                ("must_be_whole_num",),
            ],
        },
    },
    # ── Rate (e.g. "at a rate of 2 to 5 litres per minute") ──────────────────
    "rate_other": {
        "confident": {
            "fields": [
                "rateRange_low",
                "rateRange_high",
                "rateQuantity_value",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", HIGH_RATE),
            ],
        },
        "max_rules": {
            "rateRange_high": ("must_be_greater_than", "rateRange_low"),
        },
    },
    # ── Frequency (e.g. "4 times per day") ────────────────────────────────────
    "frequency": {
        "confident": {
            "fields": [
                "frequencyBare_frequency",
                "frequencyBare_frequencyMax",
                "frequencyWithMethod_frequency",
                "frequencyWithMethod_frequencyMax",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", HIGH_FREQUENCY),
                ("must_be_whole_num",),
            ],
        },
        "max_rules": {
            "frequencyBare_frequencyMax": (
                "must_be_greater_than",
                "frequencyBare_frequency",
            ),
            "frequencyWithMethod_frequencyMax": (
                "must_be_greater_than",
                "frequencyWithMethod_frequency",
            ),
            "frequencyWithMethod_frequency": ("avoid_zero", False),
            "frequencyBare_frequency": ("avoid_zero", False),
        },
    },
    # ── Count (e.g. "2 times", "once") ────────────────────────────────────────
    "count": {
        "confident": {
            "fields": [
                "count_count",
                "count_countMax",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", HIGH_COUNT),
                ("must_be_whole_num",),
            ],
        },
        "max_rules": {
            "count_countMax": ("must_be_greater_than", "count_count"),
        },
    },
    # ── Period (e.g. "every 4 days") ──────────────────────────────────────────
    "period": {
        "confident": {
            "fields": [
                "periodElement_period",
                "periodElement_periodMax",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", HIGH_PERIOD),
                ("must_be_whole_num",),
            ],
        },
        "max_rules": {
            "periodElement_periodMax": ("must_be_greater_than", "periodElement_period"),
        },
    },
    # ── When / Offset (e.g. "30 minutes after food") ─────────────────────────
    "when_offset": {
        "confident": {
            "fields": [
                "whenBare_offset",
                "whenBare_offsetMax",
                "whenWithMethod_offset",
                "whenWithMethod_offsetMax",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", HIGH_OFFSET),
                ("must_be_whole_num",),
            ],
        },
        "max_rules": {
            "whenBare_offsetMax": ("must_be_greater_than", "whenBare_offset"),
            "whenWithMethod_offsetMax": (
                "must_be_greater_than",
                "whenWithMethod_offset",
            ),
        },
    },
    # ── Milligram (e.g. "500mg", "4 to 5 ml") ────────────────────────────────
    "milligram": {
        "confident": {
            "fields": [
                "milligramValue_value",
                "milligramMax_value",
                "milligramMax_valueMax",
            ],
            "rules": [
                ("no_negatives",),
                ("below", HIGH_MILLIGRAM),
                ("avoid_emergency_numbers",),
                ("avoid_years",),
                ("avoid_times",),
            ],
        },
        "max_rules": {
            "milligramMax_valueMax": ("must_be_greater_than", "milligramMax_value"),
            "milligramMax_value": ("avoid_zero", False),
        },
    },
    # ── Duration (e.g. "for 5 days", "over 2 weeks") ─────────────────────────
    "duration": {
        "confident": {
            "fields": [
                "durationValue_value",
                "durationMax_value",
                "boundsDuration_value",
                "boundsDuration_valueMax",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", HIGH_DURATION),
                ("must_be_whole_num",),
            ],
        },
        "max_rules": {
            "boundsDuration_valueMax": ("must_be_greater_than", "boundsDuration_value"),
        },
    },
    # ── Max dose (e.g. "maximum of 8 tablets in a day") ───────────────────────
    "max_dose": {
        "confident": {
            "fields": [
                "maxDosePerPeriod_num_value",
                "maxDosePerPeriod_denom_value",
                "maxDosePerAdministration_value",
                "maxDosePerLifetime_value",
            ],
            "rules": [
                ("no_negatives",),
                ("avoid_zero",),
                ("below", HIGH_MAX_DOSE),
                ("must_be_whole_num",),
            ],
        },
    },
}


# ── Build flat NUMERIC_VALIDATION_RULES from groups ───────────────────────────


def _build_rules_from_groups(groups):
    rules = {}
    for group_config in groups.values():
        max_rules = group_config.get("max_rules", {})
        for tier_name, tier in group_config.items():
            if tier_name == "max_rules":
                continue
            for field in tier["fields"]:
                field_rules = list(tier["rules"])
                if field in max_rules:
                    field_rules.append(max_rules[field])
                rules[field] = field_rules
    return rules


NUMERIC_VALIDATION_RULES = _build_rules_from_groups(VALIDATION_GROUPS)
